### ISSUE TITLE
Test failing with tensorflow 2.17

### ISSUE THREAD

**Issue by EWitting** [DataCanvasIO/DeepTables#96]
**System information**
- Windows 11
- Python 3.11.9
- DeepTables 0.2.6
- Tensorflow 2.17.0

**Describe the current behavior**
Running the standard test snippet, as well as trying to train a model, fails on:
```
  File "C:\Me\Epoch\Code\mcts\.venv\Lib\site-packages\deeptables\models\deeptable.py", line 363, in fit
    history = model.fit(X, y, batch_size=batch_size, epochs=epochs, verbose=verbose, shuffle=shuffle,
    history = model.fit(X, y, batch_size=batch_size, epochs=epochs, verbose=verbose, shuffle=shuffle,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Me\Epoch\Code\mcts\.venv\Lib\site-packages\deeptables\models\deepmodel.py", line 106, in fit
    history = self.model.fit(train_data,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Me\Epoch\Code\mcts\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Me\Epoch\Code\mcts\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler
    return fn(*args, **kwargs)
                  ^^^^^^^^^^^^^
TypeError: TensorFlowTrainer.fit() got an unexpected keyword argument 'max_queue_size'
```

**Standalone code to reproduce the issue**
`python -c "from deeptables.utils.quicktest import test; test()"`

**Suspected cause**
`max_queue_size` ,`workers`, and `use_multiprocessing` are passed. These appear to not exist in tensorflow 2.17, although they did in older versions. Downgrading to tensorflow==2.15.0 made the test pass. I am reporting this as a bug as there is no constraint mentioned anywhere about supported versions, only >2.4 in the requirements.txt.

**Comment by Pun-it** [comment]
Use TensorFlow 2.15.0 or below, as far as I am aware support for 2.15.0 > is not available.

**Comment by oaksharks** [comment]
@EWitting @Pun-it ,
Hey guys,  glad to tell you that now it works with tensorflow up to version 2.18 on master branch latest code.
